### ISSUE TITLE
Parse allowable values for arguments

### ISSUE THREAD

**Issue by zeke** [zeke/electron-docs-linter#15]
Some methods have arguments with a specific set of allowable values. These values are denoted by a list following the argument:

```
* `saveType` String - Specify the save type.
  * `HTMLOnly` - Save only the HTML of the page.
  * `HTMLComplete` - Save complete-html page.
  * `MHTML` - Save complete-html page as MHTML.
```

This nested list style is very similar to that used by arguments that are objects:

```
* `screenSize` Object - Set the emulated screen size (screenPosition == mobile)
  * `width` Integer - Set the emulated screen width
  * `height` Integer - Set the emulated screen height
```

Somehow I need to differentiate between these two cases when parsing. I see two things that signal a difference:

1. The allowable values seem to always be nested under a `String` argument. Looking for instances of other ENUM-like value lists that aren't strings, but haven't found any yet.
1. The object properties have to have a type, e.g. `Integer` in the above example.

Which of these differences do you think I should use as a signal when parsing? Or maybe there's another better technique that I haven't thought of...

cc @zcbenz @kevinsawicki @jlord

**Comment by kevinsawicki** [comment]
> Which of these differences do you think I should use as a signal when parsing?

I'd say option 1, an non-Object with a sublist is assumed to be the enum values, Objects with a sublist are property keys
